In [1]:
# Q1, Task1

def foo():
    return 5/0

# driver code
try:
    foo()
except ZeroDivisionError:
    print('A number cannot be divided by zero')
except Exception:
    print('Default exception')

A number cannot be divided by zero


In [6]:
# Q1, Task2

subjects=['Americans', 'Indians']
verbs=['play', 'watch']
objects=['Baseball', 'Cricket']

print(''.join([fLst+' ' +sLst+' '+tLst+'\n' for fLst in subjects for sLst in verbs for tLst in objects]))

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket



In [2]:
# Q1, Task3

import numpy as np
x = np.array([5, 2, 3, 6])
N = 3
print(np.vander(x, N))

[[25  5  1]
 [ 4  2  1]
 [ 9  3  1]
 [36  6  1]]
